import 'package:ephysicsapp/globals/colors.dart';
import 'package:ephysicsapp/widgets/popUps.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';

class AddChapter extends StatefulWidget {
  final String section;
  const AddChapter({Key? key, required this.section}) : super(key: key);

  @override
  State<AddChapter> createState() => _AddChapterState();
}

class _AddChapterState extends State<AddChapter> {

  TextEditingController chapterNameController = TextEditingController();
  TextEditingController chapterNoController = TextEditingController();


  void _createNewDoc() {
    print('Adding Chapter');

    // Reference to the Firebase Realtime Database
    DatabaseReference sakecReference = FirebaseDatabase.instance.ref().child(widget.section);

    // Generate a UUID
    var uuid = Uuid().v4();

    // Data to be added to the chapter node
    Map<String, dynamic> chapterData = {
      'moduleID': uuid,
      'moduleNo' : int.tryParse(chapterNoController.text) ?? 0,
      'moduleName': chapterNameController.text,
    };

    // Adding a new child node under the '1' node with the generated UUID
    DatabaseReference newChapterRef = sakecReference.child(uuid);
    newChapterRef.set(chapterData).then((_) {
      // Print the autogenerated UUID (optional)
      print('Chapter UUID: $uuid');

      // Clear the text field after adding the chapter
      chapterNameController.clear();
      chapterNoController.clear();

      showToast('New Chapter Added');
      Navigator.pop(context);
    }).catchError((error) {
      // Handle any errors that occur during the process
      print('Error adding chapter: $error');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: color1,
        appBar: AppBar(
          title: Text("Add New Chapter"),
        ),
        body: Container(
          padding: EdgeInsets.symmetric(horizontal:20),
          child:Form(
            //key: _formKeyValue,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[

                TextFormField(
                  controller: chapterNameController,
                  validator: (value){
                    if(value!.isEmpty)
                      return "Enter chapter name";
                    else return null;
                  },
                  decoration: InputDecoration(
                    labelText: "Enter chapter name",
                    fillColor: Colors.white,
                    focusedBorder: OutlineInputBorder(
                      borderSide: BorderSide(color: Colors.blue, width: 2.0),
                    ),
                  ),
                ),

                TextFormField(
                  controller: chapterNoController,
                  validator: (value){
                    if(value!.isEmpty)
                      return "Enter chapter number";
                    else return null;
                  },
                  decoration: InputDecoration(
                    labelText: "Enter chapter number",
                    fillColor: Colors.white,
                    focusedBorder: OutlineInputBorder(
                      borderSide: BorderSide(color: Colors.blue, width: 2.0),
                    ),
                  ),
                ),

                SizedBox(height: 20),
                ElevatedButton(
                  child: Text('Add Chapter', style: TextStyle(color: Colors.white),),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.deepPurple,
                  ),
                  onPressed: _createNewDoc,
                ),
              ],
            ),
          ),

        ));
  }
}
